# Generated by Django 2.2 on 2020-04-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='up_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
